apiVersion: couchbase.com/v1
kind: CouchbaseCluster
metadata:
  name: cb-op-aks-workshop
spec:
  baseImage: couchbase/server
  version: enterprise-6.0.2
  authSecret: cb-example-auth
  exposeAdminConsole: true
  adminConsoleServices:
    - data
  exposedFeatures:
    - xdcr
  exposedFeatureServiceType: NodePort
  cluster:
    dataServiceMemoryQuota: 1024
    indexServiceMemoryQuota: 1024
    searchServiceMemoryQuota: 1024
    eventingServiceMemoryQuota: 1024
    analyticsServiceMemoryQuota: 1024
    indexStorageSetting: memory_optimized
    autoFailoverTimeout: 5
    autoFailoverMaxCount: 3
    autoFailoverOnDataDiskIssues: true
    autoFailoverOnDataDiskIssuesTimePeriod: 120
    autoFailoverServerGroup: false
  buckets:
    - name: default
      type: couchbase
      memoryQuota: 128
      replicas: 1
      ioPriority: high
      evictionPolicy: fullEviction
      conflictResolution: seqno
      enableFlush: true
      enableIndexReplica: false
  servers:
    - size: 3
      name: data
      services:
        - data
      pod:
        volumeMounts:
          default: couchbase  # /opt/couchbase/var/lib/couchbase
          data: couchbase     # /mnt/data
    - size: 1
      name: query
      services:
        - query
        - index
      pod:
        volumeMounts:
          default: couchbase
          index: couchbase     # /mnt/index
    - size: 1
      name: search
      services:
        - search
        - analytics
      pod:
        volumeMounts:
          default: couchbase
  securityContext:
    fsGroup: 1000
  volumeClaimTemplates:
    - metadata:
        name: couchbase
      spec:
        storageClassName: "managed-premium"
        resources:
          requests:
            storage: 5Gi
